Lesson1/Controllers/TrailController.cs
using Lesson1.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Lesson1.Models.ViewModels;

namespace Lesson1.Controllers
{
    public class TrailController : Controller
    {
        private static readonly HttpClient client;
        private JavaScriptSerializer jss = new JavaScriptSerializer();

        static TrailController()
        {
            client = new HttpClient();
            client.BaseAddress = new Uri("https://localhost:44340/api/");
        }
        // GET: Trail/List     
        public ActionResult List()
        {
            //communicate with trail data api to retrieve a list of trails
            //curl https://localhost:44340/api/traildata/listtrails


            string url = "traildata/listtrails";
            HttpResponseMessage response = client.GetAsync(url).Result;

            IEnumerable<TrailDto> trails = response.Content.ReadAsAsync<IEnumerable<TrailDto>>().Result;


            return View(trails);
        }

        // GET: Trail/Details/5
        public ActionResult Details(int id)
        {
            DetailsTrail ViewModel = new DetailsTrail();
            //communicate with trail data api to retrieve trails
            //curl https://localhost:44340/api/traildata/findtrail/{id}

            string url = "traildata/findTrail/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;

            TrailDto SelectedTrail = response.Content.ReadAsAsync<TrailDto>().Result;
            ViewModel.SelectedTrail = SelectedTrail;




            return View(ViewModel);
        }

        public ActionResult Error()
        {
            return View();
        }


        // GET: Trail/New
        public ActionResult New()
        {
            //string url = "traildata/listtrail";
            string url = "resortdata/listresorts";
            HttpResponseMessage response = client.GetAsync(url).Result;
            IEnumerable<ResortDto> ResortOptions = response.Content.ReadAsAsync<IEnumerable<ResortDto>>().Result;

            return View(ResortOptions);
        }

        // POST: Trail/Create
        [HttpPost]
        public ActionResult Create(Trail trail)
        {
            Debug.WriteLine("the json payload is: ");
            //Add new trail details into the system using the API

            string url = "traildata/addtrail";


            string jsonpayload = jss.Serialize(trail);
            Debug.WriteLine(jsonpayload);

            HttpContent content = new StringContent(jsonpayload);
            content.Headers.ContentType.MediaType = "application/json";

            HttpResponseMessage response = client.PostAsync(url, content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Error");
            }



        }

        // GET: Trail/Edit/5
        public ActionResult Edit(int id)
        {
            UpdateTrail ViewModel = new UpdateTrail();

            string url = "traildata/findtrail/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            TrailDto SelectedTrail = response.Content.ReadAsAsync<TrailDto>().Result;
            ViewModel.SelectedTrail = SelectedTrail;


            //all resorts to choose from when updating
            url = "resortdata/listresorts";
            response = client.GetAsync(url).Result;
            IEnumerable<ResortDto> ResortOptions = response.Content.ReadAsAsync<IEnumerable<ResortDto>>().Result;

            ViewModel.ResortOptions = ResortOptions;


            return View(ViewModel);

        }

        // POST: Trail/Update/5
        [HttpPost]
        public ActionResult Update(int id, Trail trail, HttpPostedFileBase TrailPic)
        {
            string url = "traildata/updatetrail/" + id;
            string jsonpayload = jss.Serialize(trail);

            HttpContent content = new StringContent(jsonpayload);
            content.Headers.ContentType.MediaType = "application/json";

            HttpResponseMessage response = client.PostAsync(url, content).Result;
            Debug.WriteLine(content);

            if (response.IsSuccessStatusCode && TrailPic != null)
            {
                //Updating the picture as a separate request
                url = "traildata/UploadTrailPic/" + id;

                MultipartFormDataContent requestcontent = new MultipartFormDataContent();
                HttpContent imagecontent = new StreamContent(TrailPic.InputStream);
                requestcontent.Add(imagecontent, "TrailPic", TrailPic.FileName);
                response = client.PostAsync(url, requestcontent).Result;

                return RedirectToAction("List");
            }
            else if (response.IsSuccessStatusCode)
            {
                //No image upload, but update still successful
                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Error");
            }

        }


        // GET: Trail/Delete/5
        public ActionResult DeleteConfirm(int id)
        {
            string url = "traildata/findtrail/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            TrailDto SelectedTrail = response.Content.ReadAsAsync<TrailDto>().Result;

            return View(SelectedTrail);
        }

        // POST: Trail/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            string url = "traildata/deletetrail/" + id;
            HttpContent content = new StringContent("");
            content.Headers.ContentType.MediaType = "application/json";
            HttpResponseMessage response = client.PostAsync(url, content).Result;

            if (response.IsSuccessStatusCode)
            {

                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
    }
}

Lesson1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Ontario Ski Resorts</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div id="navbar">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Ontario Ski Resorts", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Resort", "List", "Resort")</li>
                        <li>@Html.ActionLink("Trails", "List", "Trail")</li>
                        <li>@Html.ActionLink("Price", "List", "Price")</li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Ontario Ski Resorts </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>